defaults:
  - driving

train_partitions:
  # old_towns: 0.05
  # 519_195
  all: 0.082
  # 10_629
  acceleration_negative_5: 0.03  # smaller than -5 m/s^2  -> -20 AND -5
  # 47_420
  acceleration_negative_1: 0.03  # between -1 and -5 m/s^2 -> -1
  # 60_208
  acceleration_positive_1: 0.03  # between 1 and 5 m/s^2 -> 5
  # 16_817
  acceleration_positive_5: 0.03  # larger than 5 m/s^2 -> 20
  # 237_390
  # brake: 0.05
  # 23_469
  # green_light: 0.05
  # # 68_215
  # red_light: 0.07
  # 44_760
  # lateral_control_1: 0.10  # wp diff in y dir larger than 0.1 and smaller than 1 -> 1
  lateral_control_1_2: 0.12  # wp diff in y dir larger than 0.1 and smaller than 1 -> 1
  # ~ 23_600
  # lateral_control_high: 0.11  # wp diff in y dir larger than 1 -> 2 AND 5 AND 1000000
  lateral_control_higher_5: 0.12  # wp diff in y dir larger than 5 -> 5 AND 1000000
  # 20_990
  start_from_stop: 0.07
  # 49_835
  # stop_sign_close: 0.07
  # 11_813
  vehicle_front: 0.04
  vehicle_side: 0.08
  leading_object_vehicle: 0.09
  leading_object_traffic.stop: 0.07
  leading_object_traffic.traffic_light: 0.07
  leading_object_walker: 0.05
  changed_route: 0.08
  parkinglane: 0.008
  # recovery: 0.07


train_partitions_dreamer:
  all: 1.0